wp:
  image: adamyeats/docker-nginx-hhvm-bedrock

  ports:
    - "80:80"
  links:
    - db:mysql
    - memcached:memcached # Optional
  volumes:
    - .:/var/www/html
  environment:
    DB_NAME: my_wordpress_project

db:
  image: mariadb
  volumes:
    - maria_data:/data/db
  environment:
    MYSQL_ROOT_PASSWORD: root

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db
  volumes:
    - /sessions
  ports:
    - "8001:80"

memcached: # Optional, recommeded for W3 Cache users
  image: memcached

#volumes:
#  maria_data:
#    external: true